// Code generated by MockGen. DO NOT EDIT.
// Source: httpsvc.go

// Package mock_httpsvc is a generated GoMock package.
package mock_httpsvc

import (
	context "context"
	reflect "reflect"

	spec "github.com/dylannz/feature-service/spec"
	gomock "github.com/golang/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// FeaturesStatus mocks base method.
func (m *MockService) FeaturesStatus(ctx context.Context, req spec.FeaturesRequest, feature string) (*spec.FeaturesResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FeaturesStatus", ctx, req, feature)
	ret0, _ := ret[0].(*spec.FeaturesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FeaturesStatus indicates an expected call of FeaturesStatus.
func (mr *MockServiceMockRecorder) FeaturesStatus(ctx, req, feature interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FeaturesStatus", reflect.TypeOf((*MockService)(nil).FeaturesStatus), ctx, req, feature)
}
