version: 1.0

features:

  stripe_billing:
    rules:
      enable:
        - field: "customer_id"
          weight: 50 # 50% chance that the feature will be enabled for the given customer_id
          values: # explicitly include customer IDs 123 and 456
            eq:
              - "123"
              - "456"
        - field: "customer_name"
          values:
            eq:
              - "Alex" # enable the feature for any customer named 'Alex'
      disable: # disable rules override enable rules
        - field: "customer_id"
          values: # explicitly disable customers 234 and 567
            eq:
              - "234"
              - "567"
      set_vars: # set custom var 'foo' to value 'bar' if customer_id is '123'
        - field: "customer_id"
          values:
            eq:
              - "123"
          set:
            foo: bar


  profile_page_v2:
    rules:
      enable:
        # the following fields in the JSON request body will be combined and hashed:
        - fields:
            - "email"
            - "customer_id"

          # 10% chance that a customer with any given email/customer_id combination
          # will have the feature enabled.
          weight: 10

